### PR TITLE
feat: display packages versions in the side bar

### PR DESCRIPTION
**Pull request by ntarocco**
* display configured packages version at the bottom of the side bar
* closes inveniosoftware/invenio-app-rdm#2838

### CODE REVIEW

**Comment by ntarocco** [comment]
Screenshot 2024-09-11 at 22 09 03

**Review by kpsherva — APPROVED** [review]

**Review by zzacharo — APPROVED** [review]

**Review by jrcastro2 — APPROVED** [review]
Reviewed with @sakshamarora1 LGTU! 🚀

**Comment by utnapischtim** [comment]
Question: how are the versions of the packages added to the variable? is there a nice automatic solution or has it to be done by hand before of the deployment?

**Comment by utnapischtim** [comment]
my two cents: a group name would be nice. we have "Site Management", "User Management" but the package -> version has no group name. maybe something like "Dev Management" and the sub name "Package versions" to make it open for other possible use cases.

**Comment by kpsherva** [comment]
> Question: how are the versions of the packages added to the variable? is there a nice automatic solution or has it to be done by hand before of the deployment?

@utnapischtim this is how it gets propagated: https://github.com/inveniosoftware/invenio-app-rdm/pull/2839/files#diff-988eb51a0bc0a8bf6efd0b04d1bb6b6d8f24cc80504ea36699a202904a20af4dR1428

https://github.com/inveniosoftware/cookiecutter-invenio-rdm/pull/294/files

**Pull request merged**
