### PR TITLE
forms: generate & use yup validation schemas

### PR DESCRIPTION
**Pull request by mirekys**
### Description

* Fixes https://github.com/inveniosoftware/invenio-banners/issues/26 by fixing form validation of required dropdown fields.

* Some required SUI inputs cannot be validated natively by browser (e.g. Dropdown). It is possible to submit a form with a dropdown input marked as required, having undefined value.

* This PR introduces an autogenerated Yup form validation schemas to address the issue.
* Validation schema is generated based on resource's marshmallow schema.
* Currently it supports only field type (numeric, string,...) and `required` validation rules, more rules could be implemented in [`mapValidationRules`](https://github.com/inveniosoftware/invenio-administration/pull/206/files#diff-da20a075b71c96578399e37e1cd76275ebd661442ce540ac539f854a44be700cR23) function.

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [ ] I've added relevant test cases.
- [ ] I've added relevant documentation.
- [ ] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/howtos/i18n/).
- [ ] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).
    * If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Frontend**

- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines.
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines.
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines.

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Comment by kpsherva** [comment]
General comment: we tried to avoid frontend validation in favour of the marhmallow validation, mostly because there might b many customized fields, and it would get very complex. I think we are simply missing default value in the Marshmallow schema for the field, since the whole form builder is based on marshmallow schemas.

**Comment by mirekys** [comment]
Hi @kpsherva, thanks for the comment, I initially tried to solve it purely using marshmallow schema (ensuring it has a default value there & is flagged as required).

But for some form input fields (even more so, if there would be many complex custom fields), setting & honoring `required` (or things like min/max length) attribute on the field wouldn't work. In invenio banners case, it was the `Form.Dropdown` component, that doesn't forward the `required` attribute to its corresponding `<input>` tag (so the native browser validation won't work), while other simpler required inputs were still properly validated by FE.

If we decide to drop FE validation completely, it would mean the BE services for every form needs to expect & gracefully handle even completely invalid submitted data & respond with schema validation errors feedback that could possibly be feeded into formik to be reflected on FE side. I can see that as a viable option too, but currently, BE just crashes there, not raising any ValidationError.

**Comment by mirekys** [comment]
> mostly because there might be many customized fields

By customized fields you mean a planned support for Custom fields like it is in records deposit form?

**Comment by kpsherva** [comment]
> > mostly because there might be many customized fields
> 
> By customized fields you mean a planned support for Custom fields like it is in records deposit form?

Sorry, I meant complex type fields, nesting etc

**Comment by kpsherva** [comment]
followed up by DM on discord, suggested to go with backend validation fix to avoid the 500 error

**Comment by utnapischtim** [comment]
so we close this PR?

**Comment by kpsherva** [comment]
closing in favour of fixing the backend validation in https://github.com/inveniosoftware/invenio-banners/pull/28

**Pull request closed without merging**
