### PR TITLE
OAI-PMH: Improve labelling

### PR DESCRIPTION
**Pull request by Pineirin**
* closes: inveniosoftware/invenio-rdm-records#1092

Screenshot from 2022-10-03 09-55-33
Screenshot from 2022-10-03 09-55-52

### CODE REVIEW

**Comment by Pineirin** [comment]
Note for reviewers.

As can be seen in the first screenshot, in the dropdown menu on the search, the label of the selected option is not the same one that appears on the list of eligible sorting options (for example: "Set name" vs "Name").

I kept it this way as it seemed to me an intentional design choice (after reading how the code works). Still in case that both the list and the selected option should match, I can propose three quick solutions.

1 - Override the Sort component for OAI-PMH sets in order to make the selected option label the title defined in the configuration (currently we use a parsed version of the key defined in the configuration).

2 - Modify the Sort component defined on invenio-search-ui to make the selected option label the title defined in the configuration.

3 - Modify the format_sortoptions parsing to be able to define a label specifically for the selected sort option.

**Comment by jennur** [comment]
I think the name on the trigger and in the dropdown should be the same, as it refers to the selected value. I.e. here it looks like "Name" and "Set name" are two different options for sorting. Imo this should be the default behaviour of the Sort component like you suggest in # 2.

**Comment by Pineirin** [comment]
I agree, but it is very clear that this choice was intentionally made given that for displaying the key as a the selected sort option a fairly complex regex had to be created, so would like to have more consensus before implementing.

Maybe the rationale was that it could make sense that the selected sort option was just a word while the list offered more descriptive information.

**Comment by kpsherva** [comment]
Please fix as described in #2, in a separate PR. I will merge this one

**Review by kpsherva — APPROVED** [review]

**Pull request merged**
